### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by eskan** [vidrioapp/vidrio-translations#30]
Hi Vidrio,
there 's some missing strings to translate : "Watermark" and "Provide feedback ..."
Thanks for this tool, regards,

<img width="270" alt="Capture d’écran 2020-11-05 à 09 56 52" src="https://user-images.githubusercontent.com/1148360/98219679-9f456480-1f4d-11eb-84b9-5e45d11f4440.png">

**Comment by jameshfisher** [comment]
Hey @eskan - thanks for pointing this out; I've added default translations for these [here](https://github.com/vidrioapp/vidrio-translations/blob/master/fr.lproj/Localizable.strings) - I used Google Translate; if you have better translations, please correct me in a PR! 😅
